"""建库路径的守卫测试。

事实来源：openspec/changes/data-model-permission/design.md D8
          openspec/changes/data-model-permission/tasks.md 1.5（验证：源码内不出现 create_all）

D8：真实库**唯一**的建表入口是 `alembic upgrade head`。这条不变量靠「没人写
第二个入口」维持 —— 而人会忘，所以钉成测试。

**断言走 AST 而非子串匹配**。`scripts/init_db.py` 的 docstring 里正当地提到了
`create_all` 这个词（解释它为什么被禁），子串匹配会把这些解释性文字判成违规，
于是把注释删掉才能让测试变绿 —— 正好把最有价值的那段"为什么"挤掉。要禁的是
**调用**，不是这个字符串本身。

后续测试落点（阶段二内，见 tasks）：2.7 / 3.5 / 4.x / 5.x / 6.x 各自的
「`autogenerate` 产生空 diff」断言也属于本文件 —— 它们同样在守 D8。
"""
from __future__ import annotations

import ast
from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect
from sqlalchemy.engine import Engine

pytestmark = pytest.mark.model

BACKEND_DIR = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = BACKEND_DIR / "scripts"
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"


#: 真实库的建表入口白名单 —— 只有迁移。
GUARDED_SOURCES = (SCRIPTS_DIR / "init_db.py", SCRIPTS_DIR / "seed_dev.py")


def _create_all_calls(path: Path) -> list[int]:
    """返回源码中 `*.create_all(...)` 调用的行号。"""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    hits: list[int] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if isinstance(func, ast.Attribute) and func.attr == "create_all":
            hits.append(node.lineno)
    return hits


@pytest.mark.parametrize("path", GUARDED_SOURCES, ids=lambda p: p.name)
def test_build_scripts_never_call_create_all(path: Path) -> None:
    """建库脚本不得调用 `create_all`（D8：两条建库路径必然漂移）。

    漂移的具体后果：`create_all` 建出的库没有 `alembic_version` 记录，后续迁移
    会在它上面从头 ALTER，于是要么报「表已存在」，要么更糟 —— 静默跳列。
    """
    assert path.exists(), f"守卫目标缺失：{path}"
    assert _create_all_calls(path) == [], (
        f"{path.name} 出现了 create_all 调用；真实库必须只经 alembic 迁移建表（D8）"
    )


def test_guard_would_actually_catch_a_violation(tmp_path: Path) -> None:
    """守卫自检：若检测逻辑失效（例如 AST 遍历写错），上面的断言会静默变成空跑。

    用一个必然违规的样本证明检测器真的会报 —— 否则「通过」可能只是没检出。
    """
    sample = tmp_path / "offender.py"
    sample.write_text(
        "from app.models.base import Base\n\n"
        "def build(engine):\n"
        "    Base.metadata.create_all(engine)\n",
        encoding="utf-8",
    )
    assert _create_all_calls(sample) == [4]


# ---------------------------------------------------------------- 2.7 迁移落地

#: 主数据链 6 张表（tasks.md §2）。
MASTER_DATA_TABLES = frozenset(
    {"warehouses", "aisles", "locations", "aisle_stations", "materials", "batches"}
)


def _alembic_config() -> Config:
    cfg = Config(str(ALEMBIC_INI))
    # 与 scripts/init_db.py 同一处置：无论 cwd 在哪，env.py 的 `import app.models` 都能解析。
    cfg.set_main_option("prepend_sys_path", str(BACKEND_DIR))
    return cfg


@pytest.fixture
def migrated_engine(tmp_path: Path) -> Iterator[Engine]:
    """在**临时文件库**上跑完整迁移链（`upgrade head`）。

    为什么不在 `conftest.py` 的内存库上跑：内存库是 `create_all` 建的（D12），
    根本没有迁移参与 —— 拿它验「迁移建出的 schema 与模型一致」是同义反复。
    要验的是「迁移脚本本身写对了」，必须让迁移真的跑一遍。
    也不能跑在 `app.core.db` 的引擎上：那是**真实开发库**，测试不该动它。
    故用 `config.attributes["connection"]` 把临时连接交给 env.py（见其 docstring）。
    """
    url = f"sqlite:///{(tmp_path / 'migrated.db').as_posix()}"
    eng = create_engine(url, future=True)
    try:
        with eng.begin() as connection:
            cfg = _alembic_config()
            cfg.attributes["connection"] = connection
            command.upgrade(cfg, "head")
        yield eng
    finally:
        eng.dispose()


def test_migration_builds_master_data_tables(migrated_engine: Engine) -> None:
    """`alembic upgrade head` 后 6 张表存在（tasks 2.7 的验证动作）。"""
    names = set(inspect(migrated_engine).get_table_names())

    assert MASTER_DATA_TABLES <= names, f"缺表：{MASTER_DATA_TABLES - names}"
    assert "alembic_version" in names, "建库经迁移的标志（D8）"


# ---------------------------------------------------------------- 6.7 阶段二终点：23 个实体

#: 17 号四条数据链 + 度量 / 身份 / 配置 —— 23 个实体，按 17 §一 的分组。
#: 主数据 6 · 衔接 5 · 作业 5 · KPI 1 · 身份 1 · 配置 5。
ALL_ENTITY_TABLES = frozenset({
    # 主数据链
    "warehouses", "aisles", "locations", "aisle_stations", "materials", "batches",
    # 衔接链
    "import_sessions", "snapshots", "inventory_items", "aisle_caps", "cap_alerts",
    # 作业链
    "job_orders", "recommendation_plans", "ledgers", "verifications", "deviations",
    # 度量与身份
    "kpi_snapshots", "accounts",
    # 配置与对话
    "weight_configs", "capacity_configs", "field_mapping_configs",
    "prompt_templates", "conversation_contexts",
})


def test_migration_builds_exactly_the_twenty_three_entities(migrated_engine: Engine) -> None:
    """`alembic upgrade head` 后**恰好** 23 张实体表（本阶段的终检，spec「23 实体」）。

    断言取**等于**而不是「包含」：多一张是有人绕开迁移建了表（`autogenerate` 迟早
    想删掉它，或更糟 —— 它悄悄留在库里成为第二套事实来源），少一张是某个实体的迁移
    没落地。两种都是这一阶段要拦住的，而「包含」两种都拦不住。
    """
    names = set(inspect(migrated_engine).get_table_names()) - {"alembic_version"}

    assert len(ALL_ENTITY_TABLES) == 23, "常量本身写错了，先修这个"
    assert names == ALL_ENTITY_TABLES, (
        f"多出：{names - ALL_ENTITY_TABLES}；缺少：{ALL_ENTITY_TABLES - names}"
    )


def test_metadata_declares_exactly_the_twenty_three_entities() -> None:
    """模型侧的同一件事：`Base.metadata` 里也是这 23 张表。

    上面的迁移断言验「库里有什么」，这条验「模型声明了什么」—— 两者一起才能说明
    「模型与迁移一一对应」。只查库，漏掉一个实体的模型会让 `create_all` 的内存测试库
    少一张表（D12 下模型才是测试库的事实来源），而真实库看起来完全正常。
    """
    from app.models.base import Base

    assert set(Base.metadata.tables) == ALL_ENTITY_TABLES


def test_migration_keeps_enum_check_constraint(migrated_engine: Engine) -> None:
    """库里的 `abc_class` CHECK 必须真的存在。

    这条断言看着琐碎，实为 `env.py` 那个 `include_object` 过滤器的**理由说明书**：
    Alembic 把 `sa.Enum` 生成的 CHECK 从 metadata 侧排除，比对时会把库里这条真实约束
    判成「多出来的」，于是过滤器把它在反射侧也排除掉。后来者若只看到「过滤器屏蔽了
    检查约束」，很可能误以为约束没落库而"顺手"把过滤器删掉 —— 这条断言把事实钉住：
    约束在库里，屏蔽的只是**比对**。
    """
    checks = {
        ck["name"]: ck["sqltext"]
        for ck in inspect(migrated_engine).get_check_constraints("materials")
    }
    assert "ck_materials_abc_class" in checks
    assert "'A'" in checks["ck_materials_abc_class"]


def test_autogenerate_produces_empty_diff(migrated_engine: Engine) -> None:
    """`autogenerate` 产生空 diff（tasks 2.7 / 9.1 的验收动作，D8 的漂移防线）。

    走 `command.check` 而不是 `compare_metadata`：前者会完整跑一遍 `env.py`，
    因而**自带**那里的 `include_object` 过滤器。绕开 env.py 直接比对，会把
    「枚举 CHECK 被过滤掉」这件事漏掉，得到的空 diff 与真实 autogenerate 不是一回事。
    """
    cfg = _alembic_config()
    with migrated_engine.connect() as connection:
        cfg.attributes["connection"] = connection
        command.check(cfg)  # 有 diff 会抛 AutogenerateDiffsDetected


def test_empty_diff_check_would_actually_catch_drift(migrated_engine: Engine) -> None:
    """守卫自检：证明上面那条空 diff 断言不是空跑。

    过滤器一旦写宽（例如 `include_object` 恒返回 False），空 diff 会永远为真，
    而漂移悄悄积累。这里造一个必然的差异 —— 库里多出一张模型没有的表 ——
    证明这条链路真的会报。
    """
    with migrated_engine.begin() as connection:
        connection.exec_driver_sql("CREATE TABLE drift_probe (id INTEGER PRIMARY KEY)")

    cfg = _alembic_config()
    with migrated_engine.connect() as connection:
        cfg.attributes["connection"] = connection
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(cfg)
