"""度量与身份_kpi快照_账号

Revision ID: 0559bebb5207
Revises: f01b0406d12c
Create Date: 2026-09-11 16:17:39.840715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0559bebb5207'
down_revision: Union[str, Sequence[str], None] = 'f01b0406d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('warehouse_keeper', 'planner', 'supervisor', 'admin', name='role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', 'rejected', name='account_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('initial_password_changed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts.id'], name=op.f('fk_accounts_created_by_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('username', name='uq_accounts_username')
    )
    op.create_table('kpi_snapshots',
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPUTING', 'READY', 'STALE', 'ERROR', name='kpi_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('weighted_concentration', sa.Float(), nullable=True),
    sa.Column('same_material_cross_aisle', sa.Float(), nullable=True),
    sa.Column('same_batch_cross_aisle', sa.Float(), nullable=True),
    sa.Column('adoption_rate', sa.Float(), nullable=True),
    sa.Column('placement_accuracy', sa.Float(), nullable=True),
    sa.Column('period_over_period_json', sa.JSON(), nullable=True),
    sa.Column('card_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_snapshots')),
    sa.UniqueConstraint('warehouse_id', 'period', name='uq_kpi_snapshots_warehouse_period')
    )
    with op.batch_alter_table('job_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_job_orders_confirmed_by_id_accounts'), 'accounts', ['confirmed_by_id'], ['id'])

    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_ledgers_operator_id_accounts'), 'accounts', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ledgers_operator_id_accounts'), type_='foreignkey')

    with op.batch_alter_table('job_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_job_orders_confirmed_by_id_accounts'), type_='foreignkey')

    op.drop_table('kpi_snapshots')
    op.drop_table('accounts')
    # ### end Alembic commands ###
