"""衔接链：导入会话/快照基线/库存分布/巷道容量/容量告警

Revision ID: 2c10a7d2b5bf
Revises: 56fbc88f62e8
Create Date: 2026-09-11 16:01:57.198340

事实来源：17-数据模型设计 §三（数据衔接实体）、§10.4 / §10.5（回执与 cap 快照 JSON）
          16-数据衔接与 cap 自维护 §3（状态机与 ImportSession）、§6.5（cap 异常与告警）
          openspec/changes/data-model-permission/design.md D1 / D2 / D4 / D5 / D8
          tasks.md §3（衔接链 5 实体，tasks 3.1~3.6）

由 `alembic revision --autogenerate` 生成，**未手工调整 DDL** —— 五张表与
`app/models/linkage.py` 逐列一致。可复验：`alembic check` 报「No new upgrade
operations detected」（对应 tasks 3.6 的验证动作，已钉成
`tests/models/test_migrations.py::test_autogenerate_produces_empty_diff`）。

四条读这份迁移时要知道的事：

  - **两条枚举 CHECK 不在本文件的约束列表里**：`ck_import_sessions_import_status` 与
    `ck_cap_alerts_alert_kind` 由 `sa.Enum` 在 DDL 生成时渲染。后者带**中文取值**
    （`'负cap' / '超总格' / '增量失败' / '漂移超阈值'`，16 §6.5 的四类 cap 异常）——
    按文档原文存，不翻译成代号。比对侧的副作用见 `migrations/env.py`
    的 `_type_generated_checks`。
  - **`cap_alerts.ledger_txn_id` 在这一版里没有外键**，这是刻意的：design.md D5 要求它是
    外键，目标表 `ledgers` 属作业链（§4）。SQLAlchemy 的 `ForeignKey` 目标表必须已在
    `Base.metadata` 中，否则编译 DDL 时抛 `NoReferencedTableError` —— 先声明会让本组
    的建表与测试全跑不起来。**§4 落地 `ledgers` 后必须补**：用
    `op.batch_alter_table("cap_alerts")` 加外键（SQLite 改约束只能靠 batch 重建），
    并同时收紧 `tests/logic/test_cap_alert.py` 里「两个都非空」那条用例的断言。
    登记在 tasks.md 9.4b。
  - **`inventory_items` / `aisle_caps` 不建指向主数据的外键**（`locations` / `batches` /
    `materials` / `aisles`）：快照必须能记录「源文件里有、主数据还没建」的行
    （16 A.5 #4 把料号匹配列为**校验规则**），而巷道/库位本就由快照派生（16 A.4）——
    两个方向都要，就成了循环依赖。唯一键落在业务列上，与 16 A.4 的
    「库存行标识 = 库位号 + 批号（+ 料号）」一致。
  - **`aisle_caps` 的唯一约束同时是性能索引**：`(warehouse_id, snapshot_id, aisle_no)`
    的前缀正好覆盖 design.md 性能目标表要求的 cap 查询路径（SLA ≤100ms），
    故不另建重复索引；列序被 `tests/models/test_linkage.py` 钉住。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c10a7d2b5bf'
down_revision: Union[str, Sequence[str], None] = '56fbc88f62e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('session_no', sa.String(length=32), nullable=False),
    sa.Column('import_batch_no', sa.String(length=32), nullable=False),
    sa.Column('data_time', sa.DateTime(), nullable=False),
    sa.Column('files_json', sa.JSON(), nullable=True),
    sa.Column('receipt_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'VALIDATED', 'FAILED', 'IMPORTING', 'IMPORTED', 'BASELINE', 'DISCARDED', name='import_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('snapshot_version_no', sa.Integer(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('validating_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('baselined_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_sessions')),
    sa.UniqueConstraint('warehouse_id', 'session_no', name='uq_import_sessions_warehouse_session_no')
    )
    op.create_table('snapshots',
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('cap_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('import_session_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_session_id'], ['import_sessions.id'], name=op.f('fk_snapshots_import_session_id_import_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots')),
    sa.UniqueConstraint('warehouse_id', 'version_no', name='uq_snapshots_warehouse_version_no')
    )
    op.create_table('aisle_caps',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('aisle_no', sa.String(length=2), nullable=False),
    sa.Column('cap_total', sa.Integer(), nullable=False),
    sa.Column('cap_reserved', sa.Integer(), nullable=False),
    sa.Column('cap_usable', sa.Integer(), nullable=False),
    sa.Column('is_near_station', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(aisle_no) = 2', name=op.f('ck_aisle_caps_aisle_no_len2')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], name=op.f('fk_aisle_caps_snapshot_id_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aisle_caps')),
    sa.UniqueConstraint('warehouse_id', 'snapshot_id', 'aisle_no', name='uq_aisle_caps_snapshot_aisle_no')
    )
    op.create_table('cap_alerts',
    sa.Column('alert_kind', sa.Enum('负cap', '超总格', '增量失败', '漂移超阈值', name='alert_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('aisle_no', sa.String(length=2), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('ledger_txn_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(snapshot_id IS NULL) <> (ledger_txn_id IS NULL)', name=op.f('ck_cap_alerts_alert_source_exactly_one')),
    sa.CheckConstraint('length(aisle_no) = 2', name=op.f('ck_cap_alerts_aisle_no_len2')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], name=op.f('fk_cap_alerts_snapshot_id_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cap_alerts'))
    )
    op.create_table('inventory_items',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=32), nullable=True),
    sa.Column('location_code', sa.String(length=6), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=256), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('item_status', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(location_code) = 6', name=op.f('ck_inventory_items_location_code_len6')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_inventory_items_qty_positive')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], name=op.f('fk_inventory_items_snapshot_id_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('warehouse_id', 'snapshot_id', 'location_code', 'batch_no', 'material_code', name='uq_inventory_items_snapshot_location_batch_material')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    op.drop_table('cap_alerts')
    op.drop_table('aisle_caps')
    op.drop_table('snapshots')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
