"""冷路径链_三实体

Revision ID: 3c9f7e2a1b04
Revises: b1e5a3c7d9f2
Create Date: 2026-09-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9f7e2a1b04'
down_revision: Union[str, Sequence[str], None] = 'b1e5a3c7d9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('capability_kind', sa.Enum('KPI 解读', '偏离归因', '权重调优', '移库方案', name='capability', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ADOPTED', 'DISMISSED', name='ai_suggestion_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_suggestions'))
    )
    op.create_table('ai_cost_quotas',
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('tokens_consumed >= 0', name=op.f('ck_ai_cost_quotas_tokens_consumed_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_cost_quotas')),
    sa.UniqueConstraint('warehouse_id', 'period', name='uq_ai_cost_quotas_warehouse_period')
    )
    op.create_table('conversation_logs',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('question_raw', sa.Text(), nullable=False),
    sa.Column('question_redacted', sa.Text(), nullable=True),
    sa.Column('llm_output', sa.Text(), nullable=True),
    sa.Column('hit_cold_path', sa.Boolean(), nullable=False),
    sa.Column('slots_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_conversation_logs_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_logs')
    op.drop_table('ai_cost_quotas')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
