"""主数据链：仓库/巷道/库位/巷道-站台/物料/批次

Revision ID: 56fbc88f62e8
Revises: d7f6f1ec856a
Create Date: 2026-09-11 15:13:43.339343

事实来源：17-数据模型设计 §二（主数据实体）、§九（abc_class 枚举）
          openspec/changes/data-model-permission/design.md D8（模型改动必带同 commit 迁移）
          tasks.md §2（主数据链 6 实体，tasks 2.1~2.7）

由 `alembic revision --autogenerate` 生成，**未手工调整 DDL** —— 六张表与
`app/models/master_data.py` 逐列一致。可复验：`alembic check` 报「No new upgrade
operations detected」（对应 tasks 2.7 的验证动作，已钉成
`tests/models/test_migrations.py::test_autogenerate_produces_empty_diff`）。

两条读这份迁移时要知道的事：

  - **`abc_class` 的 CHECK 不在本文件的约束列表里**，它由 `sa.Enum` 在 DDL 生成时渲染，
    库里长这样：`CONSTRAINT ck_materials_abc_class CHECK (abc_class IN ('A','B','C'))`。
    别因为文件里看不到就以为 D3 的取值约束没落库（同理适用于后续所有枚举列）。
    比对侧的副作用与应对见 `migrations/env.py` 的 `_type_generated_checks`。
  - **`locations` 没有指向 `aisles` 的外键** —— 取而代之的是三条 CHECK，把库位编码规则
    （前 2 位巷道 / 中 2 位层列 / 后 2 位格，`16` §4.2「已实证」）钉在库里。
    `aisle_stations` 相反：建了指向 `aisles` 唯一键的复合外键（17 ER 图 `||--||`）。
    两处取舍的理由见 `app/models/master_data.py` 的模块 docstring。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fbc88f62e8'
down_revision: Union[str, Sequence[str], None] = 'd7f6f1ec856a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisles',
    sa.Column('aisle_no', sa.String(length=2), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=True),
    sa.Column('is_near_station', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(aisle_no) = 2', name=op.f('ck_aisles_aisle_no_len2')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aisles')),
    sa.UniqueConstraint('warehouse_id', 'aisle_no', name='uq_aisles_warehouse_aisle_no')
    )
    op.create_table('locations',
    sa.Column('location_code', sa.String(length=6), nullable=False),
    sa.Column('aisle_no', sa.String(length=2), nullable=False),
    sa.Column('layer_column_no', sa.String(length=2), nullable=False),
    sa.Column('cell_no', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(location_code) = 6', name=op.f('ck_locations_location_code_len6')),
    sa.CheckConstraint('substr(location_code, 1, 2) = aisle_no', name=op.f('ck_locations_location_code_aisle')),
    sa.CheckConstraint('substr(location_code, 3, 2) = layer_column_no', name=op.f('ck_locations_location_code_layer_column')),
    sa.CheckConstraint('substr(location_code, 5, 2) = cell_no', name=op.f('ck_locations_location_code_cell')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('warehouse_id', 'location_code', name='uq_locations_warehouse_location_code')
    )
    op.create_table('materials',
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=256), nullable=True),
    sa.Column('abc_class', sa.Enum('A', 'B', 'C', name='abc_class', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('units_per_carton', sa.Integer(), nullable=True),
    sa.Column('cartons_per_pallet', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('warehouse_id', 'material_code', name='uq_materials_warehouse_material_code')
    )
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plant_code', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('warehouse_id', name='uq_warehouses_warehouse_id')
    )
    op.create_table('aisle_stations',
    sa.Column('aisle_no', sa.String(length=2), nullable=False),
    sa.Column('station_code', sa.String(length=32), nullable=False),
    sa.Column('distance_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id', 'aisle_no'], ['aisles.warehouse_id', 'aisles.aisle_no'], name=op.f('fk_aisle_stations_warehouse_id_aisles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aisle_stations')),
    sa.UniqueConstraint('warehouse_id', 'aisle_no', name='uq_aisle_stations_warehouse_aisle_no')
    )
    op.create_table('batches',
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_batches_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('warehouse_id', 'batch_no', name='uq_batches_warehouse_batch_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    op.drop_table('aisle_stations')
    op.drop_table('warehouses')
    op.drop_table('materials')
    op.drop_table('locations')
    op.drop_table('aisles')
    # ### end Alembic commands ###
