"""配置与对话_五实体

Revision ID: 62cdb8b54011
Revises: 0559bebb5207
Create Date: 2026-09-11 16:23:17.318803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cdb8b54011'
down_revision: Union[str, Sequence[str], None] = '0559bebb5207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_configs',
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('near_station_reserved_ratio', sa.Float(), nullable=False),
    sa.Column('reserved_release_at', sa.Time(), nullable=False),
    sa.Column('concentration_n', sa.Integer(), nullable=False),
    sa.Column('same_material_cross_aisle_threshold', sa.Integer(), nullable=False),
    sa.Column('same_batch_cross_aisle_threshold', sa.Integer(), nullable=False),
    sa.Column('cap_drift_alert_threshold', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cap_drift_alert_threshold > 0.0', name=op.f('ck_capacity_configs_cap_drift_alert_threshold_positive')),
    sa.CheckConstraint('concentration_n >= 1', name=op.f('ck_capacity_configs_concentration_n_positive')),
    sa.CheckConstraint('near_station_reserved_ratio BETWEEN 0.0 AND 1.0', name=op.f('ck_capacity_configs_near_station_reserved_ratio_range')),
    sa.CheckConstraint('same_batch_cross_aisle_threshold >= 1', name=op.f('ck_capacity_configs_same_batch_cross_aisle_threshold_positive')),
    sa.CheckConstraint('same_material_cross_aisle_threshold >= 1', name=op.f('ck_capacity_configs_same_material_cross_aisle_threshold_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_configs')),
    sa.UniqueConstraint('warehouse_id', 'version_no', name='uq_capacity_configs_warehouse_version')
    )
    op.create_table('field_mapping_configs',
    sa.Column('plant_code', sa.String(length=32), nullable=False),
    sa.Column('file_type', sa.Enum('PO', 'DO', 'INV', name='file_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_mapping_configs')),
    sa.UniqueConstraint('warehouse_id', 'plant_code', 'file_type', name='uq_field_mapping_configs_warehouse_plant_file_type')
    )
    op.create_table('prompt_templates',
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=False),
    sa.Column('capability', sa.Enum('KPI 解读', '偏离归因', '权重调优', '移库方案', name='capability', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('warehouse_id', 'template_id', name='uq_prompt_templates_warehouse_template_id')
    )
    op.create_table('weight_configs',
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('weight_abc', sa.Float(), nullable=False),
    sa.Column('weight_cap', sa.Float(), nullable=False),
    sa.Column('weight_existing', sa.Float(), nullable=False),
    sa.Column('weight_station', sa.Float(), nullable=False),
    sa.Column('weight_batch', sa.Float(), nullable=False),
    sa.Column('weight_continuity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('weight_abc BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_abc_range')),
    sa.CheckConstraint('weight_batch BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_batch_range')),
    sa.CheckConstraint('weight_cap BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_cap_range')),
    sa.CheckConstraint('weight_continuity BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_continuity_range')),
    sa.CheckConstraint('weight_existing BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_existing_range')),
    sa.CheckConstraint('weight_station BETWEEN 0.0 AND 1.0', name=op.f('ck_weight_configs_weight_station_range')),
    sa.ForeignKeyConstraint(['changed_by_id'], ['accounts.id'], name=op.f('fk_weight_configs_changed_by_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_configs')),
    sa.UniqueConstraint('warehouse_id', 'version_no', name='uq_weight_configs_warehouse_version')
    )
    op.create_table('conversation_contexts',
    sa.Column('session_no', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('page_context', sa.String(length=64), nullable=True),
    sa.Column('recent_turns_json', sa.JSON(), nullable=True),
    sa.Column('pending_write_json', sa.JSON(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_conversation_contexts_account_id_accounts')),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], name=op.f('fk_conversation_contexts_job_order_id_job_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_contexts')),
    sa.UniqueConstraint('warehouse_id', 'session_no', name='uq_conversation_contexts_warehouse_session_no')
    )
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity_config_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_kpi_snapshots_capacity_config_id_capacity_configs'), 'capacity_configs', ['capacity_config_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_kpi_snapshots_capacity_config_id_capacity_configs'), type_='foreignkey')
        batch_op.drop_column('capacity_config_id')

    op.drop_table('conversation_contexts')
    op.drop_table('weight_configs')
    op.drop_table('prompt_templates')
    op.drop_table('field_mapping_configs')
    op.drop_table('capacity_configs')
    # ### end Alembic commands ###
