"""作业链_作业单_推荐方案_台账_后验_偏离批次

Revision ID: f01b0406d12c
Revises: 2c10a7d2b5bf
Create Date: 2026-09-11 16:10:42.217490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01b0406d12c'
down_revision: Union[str, Sequence[str], None] = '2c10a7d2b5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_orders',
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('line_no', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.Enum('INBOUND', 'OUTBOUND', 'RELOCATE', name='job_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('bulk_batch_no', sa.String(length=32), nullable=True),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=256), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('abc_class', sa.Enum('A', 'B', 'C', name='abc_class', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PLANNED', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'EXECUTED', 'VERIFIED', name='job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.Enum('ACCEPT', 'TUNE', 'REJECT', name='disposition', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_card_digest', sa.Text(), nullable=True),
    sa.Column('tune_detail', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('actual_location_code', sa.String(length=6), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actual_location_code IS NULL OR length(actual_location_code) = 6', name=op.f('ck_job_orders_actual_location_code_len6')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_orders')),
    sa.UniqueConstraint('warehouse_id', 'job_type', 'order_no', 'line_no', name='uq_job_orders_warehouse_type_order_line')
    )
    op.create_table('deviations',
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('material_code', sa.String(length=64), nullable=True),
    sa.Column('actual_cross_aisle', sa.Integer(), nullable=False),
    sa.Column('threshold_cross_aisle', sa.Integer(), nullable=False),
    sa.Column('cause_kind', sa.Enum('新入库收拢不达标', '历史库存拖累', name='cause_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('未处理', '已发起移库', '已改善', name='deviation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('relocate_job_order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(status <> '已发起移库') OR (relocate_job_order_id IS NOT NULL)", name=op.f('ck_deviations_relocate_started_needs_job_order')),
    sa.CheckConstraint('(batch_no IS NOT NULL) OR (material_code IS NOT NULL)', name=op.f('ck_deviations_identifier_required')),
    sa.ForeignKeyConstraint(['relocate_job_order_id'], ['job_orders.id'], name=op.f('fk_deviations_relocate_job_order_id_job_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deviations'))
    )
    op.create_table('ledgers',
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('ledger_type', sa.Enum('INBOUND', 'OUTBOUND', 'RELOCATE', name='ledger_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=256), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('source_location_code', sa.String(length=6), nullable=True),
    sa.Column('target_location_code', sa.String(length=6), nullable=True),
    sa.Column('pick_path_json', sa.JSON(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degrade_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(ledger_type = 'INBOUND' AND source_location_code IS NULL AND target_location_code IS NOT NULL) OR (ledger_type = 'OUTBOUND' AND source_location_code IS NOT NULL AND target_location_code IS NULL) OR (ledger_type = 'RELOCATE' AND source_location_code IS NOT NULL AND target_location_code IS NOT NULL)", name=op.f('ck_ledgers_location_columns_by_type')),
    sa.CheckConstraint('(degraded = 0) OR (degrade_reason IS NOT NULL)', name=op.f('ck_ledgers_degrade_reason_required')),
    sa.CheckConstraint('source_location_code IS NULL OR length(source_location_code) = 6', name=op.f('ck_ledgers_source_location_code_len6')),
    sa.CheckConstraint('target_location_code IS NULL OR length(target_location_code) = 6', name=op.f('ck_ledgers_target_location_code_len6')),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], name=op.f('fk_ledgers_job_order_id_job_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledgers')),
    sa.UniqueConstraint('job_order_id', name='uq_ledgers_job_order_id')
    )
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.create_index('ix_ledgers_warehouse_order_no', ['warehouse_id', 'order_no'], unique=False)

    op.create_table('recommendation_plans',
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('plan_kind', sa.Enum('分配', '顺路取', '收拢', name='plan_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degrade_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(degraded = 0) OR (degrade_reason IS NOT NULL)', name=op.f('ck_recommendation_plans_degrade_reason_required')),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], name=op.f('fk_recommendation_plans_job_order_id_job_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_plans'))
    )
    with op.batch_alter_table('recommendation_plans', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_plans_job_order_id', ['job_order_id'], unique=False)

    op.create_table('verifications',
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('metric_kind', sa.String(length=32), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('verify_result', sa.Enum('PASS', 'DEVIATION', name='verify_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], name=op.f('fk_verifications_job_order_id_job_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications')),
    sa.UniqueConstraint('job_order_id', 'metric_kind', name='uq_verifications_job_order_metric_kind')
    )
    with op.batch_alter_table('cap_alerts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_cap_alerts_ledger_txn_id_ledgers'), 'ledgers', ['ledger_txn_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cap_alerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cap_alerts_ledger_txn_id_ledgers'), type_='foreignkey')

    op.drop_table('verifications')
    with op.batch_alter_table('recommendation_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendation_plans_job_order_id')

    op.drop_table('recommendation_plans')
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.drop_index('ix_ledgers_warehouse_order_no')

    op.drop_table('ledgers')
    op.drop_table('deviations')
    op.drop_table('job_orders')
    # ### end Alembic commands ###
